import React,{useEffect,useState}from"react";
import type{MembershipRole,OrganizationEntitlement,OrganizationInvitation,OrganizationMember,OrganizationSummary}from"@foundry/contracts";
import{api}from"./api";

export function TeamPanel({organization,onOrganizationsChanged}:{organization:OrganizationSummary;onOrganizationsChanged:()=>Promise<void>}){
  const[members,setMembers]=useState<OrganizationMember[]>([]),[entitlement,setEntitlement]=useState<OrganizationEntitlement|null>(null),[invitations,setInvitations]=useState<OrganizationInvitation[]>([]),[email,setEmail]=useState(""),[role,setRole]=useState<MembershipRole>("member"),[message,setMessage]=useState(""),[error,setError]=useState("");
  const canManage=organization.role==="owner"||organization.role==="admin",isOwner=organization.role==="owner";
  async function load(){try{setError("");const[m,e]=await Promise.all([api.members(organization.id),api.entitlements(organization.id)]);setMembers(m);setEntitlement(e);if(canManage)setInvitations(await api.invitations(organization.id));else setInvitations([])}catch(e:any){setError(e.message)}}
  useEffect(()=>{load()},[organization.id,organization.role]);
  async function invite(e:React.FormEvent){e.preventDefault();try{setError("");const r=await api.invite(organization.id,email,role);setMessage(r.invitationToken?`Development invitation token: ${r.invitationToken}`:"Invitation sent");setEmail("");await load()}catch(e:any){setError(e.message)}}
  async function changeRole(member:OrganizationMember,next:MembershipRole){try{await api.updateMemberRole(organization.id,member.id,next);await load()}catch(e:any){setError(e.message)}}
  async function remove(member:OrganizationMember){if(!confirm(`Remove ${member.email} from ${organization.name}?`))return;try{await api.removeMember(organization.id,member.id);await load()}catch(e:any){setError(e.message)}}
  async function revoke(invite:OrganizationInvitation){try{await api.revokeInvitation(organization.id,invite.id);await load()}catch(e:any){setError(e.message)}}
  async function deleteOrganization(){if(!confirm(`Delete ${organization.name} and all tenant-scoped tasks?`))return;try{await api.deleteOrganization(organization.id);await onOrganizationsChanged()}catch(e:any){setError(e.message)}}
  return <section className="teamPanel"><header><div><span className="eyebrow">WORKSPACE</span><h1>{organization.name}</h1><p className="muted">Role: {organization.role} · Plan: {entitlement?.planCode||organization.planCode} · Member limit: {entitlement?.maxMembers||organization.maxMembers}</p></div>{isOwner&&<button className="dangerButton" onClick={deleteOrganization}>Delete workspace</button>}</header>{error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}
    {canManage&&<form className="inviteForm" onSubmit={invite}><input type="email" placeholder="teammate@example.com" value={email} onChange={e=>setEmail(e.target.value)} required/><select value={role} onChange={e=>setRole(e.target.value as MembershipRole)}><option value="member">Member</option><option value="admin">Admin</option></select><button className="primary">Invite</button></form>}
    <div className="panel"><div className="panelHead"><h2>Members</h2><span>{members.length}/{entitlement?.maxMembers||organization.maxMembers}</span></div><div className="tableScroll"><table><thead><tr><th>Email</th><th>Role</th><th>Joined</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{members.map(member=><tr key={member.id}><td>{member.email}</td><td>{isOwner?<select value={member.role} onChange={e=>changeRole(member,e.target.value as MembershipRole)}><option value="owner">Owner</option><option value="admin">Admin</option><option value="member">Member</option></select>:member.role}</td><td>{new Date(member.createdAt).toLocaleDateString()}</td>{canManage&&<td><button className="ghost" disabled={member.role==="owner"} onClick={()=>remove(member)}>Remove</button></td>}</tr>)}</tbody></table></div></div>
    {canManage&&<div className="panel"><div className="panelHead"><h2>Pending invitations</h2><span>{invitations.length}</span></div>{invitations.length?<div className="tableScroll"><table><thead><tr><th>Email</th><th>Role</th><th>Expires</th><th/></tr></thead><tbody>{invitations.map(invite=><tr key={invite.id}><td>{invite.email}</td><td>{invite.role}</td><td>{new Date(invite.expiresAt).toLocaleDateString()}</td><td><button className="ghost" onClick={()=>revoke(invite)}>Revoke</button></td></tr>)}</tbody></table></div>:<div className="empty small">No pending invitations.</div>}</div>}
  </section>
}
