import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

void main()=>runApp(const FoundryApp());
class Api { Api(this.base); final String base; String? token; Future<dynamic> post(String p,Map<String,dynamic>b) async{final r=await http.post(Uri.parse('$base$p'),headers:{'content-type':'application/json',if(token!=null)'authorization':'Bearer $token'},body:jsonEncode(b));if(r.statusCode>=400)throw Exception(jsonDecode(r.body)['message']);return jsonDecode(r.body);} Future<List<dynamic>> tasks()async{final r=await http.get(Uri.parse('$base/tasks'),headers:{'authorization':'Bearer $token'});if(r.statusCode>=400)throw Exception('Unable to load tasks');return jsonDecode(r.body);} }
final api=Api(const String.fromEnvironment('API_URL',defaultValue:'http://10.0.2.2:4000'));
class FoundryApp extends StatelessWidget{const FoundryApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData.dark(useMaterial3:true).copyWith(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff8b7cff),brightness:Brightness.dark)),home:const LoginPage());}
class LoginPage extends StatefulWidget{const LoginPage({super.key});@override State<LoginPage> createState()=>_LoginPageState();}
class _LoginPageState extends State<LoginPage>{final email=TextEditingController(text:'demo@example.com'),pass=TextEditingController(text:'password123');String error='';Future<void>login()async{try{final r=await api.post('/auth/login',{'email':email.text,'password':pass.text});api.token=r['sessionToken'];if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const TasksPage()));}catch(e){setState(()=>error='$e');}}@override Widget build(BuildContext c)=>Scaffold(body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('Vibe SaaS Foundry',style:Theme.of(c).textTheme.headlineMedium),const SizedBox(height:24),TextField(controller:email,decoration:const InputDecoration(labelText:'Email')),const SizedBox(height:12),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Password')),const SizedBox(height:18),FilledButton(onPressed:login,child:const Text('Sign in')),if(error.isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:Text(error))])))));}}
class TasksPage extends StatefulWidget{const TasksPage({super.key});@override State<TasksPage> createState()=>_TasksPageState();}
class _TasksPageState extends State<TasksPage>{List<dynamic>tasks=[];String error='';@override void initState(){super.initState();load();}Future<void>load()async{try{final t=await api.tasks();setState(()=>tasks=t);}catch(e){setState(()=>error='$e');}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Tasks')),body:RefreshIndicator(onRefresh:load,child:ListView(children:[if(error.isNotEmpty)ListTile(title:Text(error)),...tasks.map((t)=>ListTile(title:Text(t['title']),subtitle:Text('${t['status']} • ${t['priority']}'),leading:const Icon(Icons.task_alt)))])));}
